[package]
name = "mitsuba_xml_gui"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = { version = "0.29", default-features = true }
image = { version = "0.25", default-features = true }
rfd = "0.15"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
